# Generated by Django 5.2 on 2025-06-22 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_delete_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Активная'), ('completed', 'Завершенная'), ('canceled', 'Отмененная')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.master')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime'],
                'constraints': [models.UniqueConstraint(fields=('master', 'datetime'), name='unique_master_datetime'), models.UniqueConstraint(fields=('user', 'datetime'), name='unique_user_datetime')],
            },
        ),
    ]
