# Generated by Django 5.2 on 2025-06-22 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_datetime_end'),
        ('services', '0003_delete_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='services.master'),
        ),
    ]
