# Generated by Django 5.1.7 on 2025-03-22 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование вида услуг')),
            ],
            options={
                'verbose_name': 'Вид услуги',
                'verbose_name_plural': 'Виды услуг',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новая услуга', max_length=100, verbose_name='Наименование')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('photo', models.ImageField(null=True, upload_to='services/', verbose_name='Фото')),
                ('min_price', models.IntegerField(verbose_name='Минимальная стоимость')),
                ('type_price', models.CharField(choices=[('fixed', 'Фиксированная цена'), ('flexible', 'Гибкая цена')], max_length=50, verbose_name='Тип цены')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.typeservice', verbose_name='Вид услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='PhotoService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateField(verbose_name='Дата добавления')),
                ('photo', models.ImageField(upload_to='gallery/', verbose_name='Фото')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='services.typeservice', verbose_name='Вид услуги')),
            ],
            options={
                'verbose_name': 'Фотогалерея',
                'verbose_name_plural': 'Фотогалерея',
            },
        ),
    ]
