# Generated by Django 5.2 on 2025-06-22 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
