# Generated by Django 5.1.7 on 2025-03-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(max_length=750, null=True, verbose_name='Описание'),
        ),
    ]
