# Generated by Django 5.2 on 2025-06-22 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_start', models.TimeField(default='09:00', verbose_name='Начало рабочего дня')),
                ('default_end', models.TimeField(default='18:00', verbose_name='Конец рабочего дня')),
                ('lunch_start', models.TimeField(default='13:00', verbose_name='Начало перерыва')),
                ('lunch_end', models.TimeField(default='14:00', verbose_name='Конец перерыва')),
                ('master', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='services.master')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата отсутствия')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Начало отсутствия')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Конец отсутствия')),
                ('reason', models.CharField(choices=[('vacation', 'Отпуск'), ('absence', 'Отсутствие'), ('day_off', 'Нерабочий день')], max_length=100, verbose_name='Причина')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='schedule.schedule')),
            ],
            options={
                'verbose_name': 'Отсутствие/отпуск',
                'verbose_name_plural': 'Отсутствия/отпуска',
            },
        ),
    ]
