# Generated by Django 5.2 on 2025-06-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayoff',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Конечная дата (для отпуска)'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отсутствия'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='end_time',
            field=models.TimeField(blank=True, default='18:00', null=True, verbose_name='Конец отсутствия'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='start_time',
            field=models.TimeField(blank=True, default='09:00', null=True, verbose_name='Начало отсутствия'),
        ),
    ]
