# Generated by Django 5.2 on 2025-06-22 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_dayoff_end_date_alter_dayoff_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Начальная дата отсутствия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Конечная дата отсутствия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='end_time',
            field=models.TimeField(default='18:00', verbose_name='Конец отсутствия'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='start_time',
            field=models.TimeField(default='09:00', verbose_name='Начало отсутствия'),
        ),
    ]
